### ISSUE TITLE
Email gets sent but not received

### ISSUE THREAD

**Issue by firstdorsal** [nodemailer/smtp-server#121] opened 2019-02-22 18:32 UTC
```
const nodemailer = require('nodemailer');

const SMTPServer = require("smtp-server").SMTPServer;

const server = new SMTPServer({
    onAuth(auth, session, callback) {
        if (auth.username !== "test" || auth.password !== "password") {
            return callback(new Error("Invalid username or password"));
        }
        console.log(mailOptions.text);
        callback(null, {
            user: "test"

        }); // where 123 is the user id or similar property
    }
});

server.on("error", err => {
    console.log("Error %s", err.message);
});

server.listen(26);


var transporter = nodemailer.createTransport({
    host: "MYDOMAINNAME/IP",
    port: 26,
    secure: false,
    auth: {
        user: "test",
        pass: "password"
    },
    tls: {
        rejectUnauthorized: false
    }
});

var mailOptions = {
    from: '"MYSITENAME"<info@MYDOMAIN.com>',
    to: 'ADRESS@TLD.com',
    subject: 'Sending Email using Node.js',
    text: 'That was easy!'
};

transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
        console.log("sendmail" + error);
    } else {
        console.log('Email sent: ' + info.response);
    }
});

```

Output is:
That was easy!
Email sent: 250 OK: message queued

i just want to send a mail with an input variable as text from my domainname to an normal gmail address;
the mail doesent get received by the gmail/ or any other adress; checked the spam folder;

**Comment by MrXyfir** [comment] 2019-03-13 02:05
You've probably solved this by now but you're just sending the mail to your own server and then doing nothing with it.

**Comment by severussnape357** [comment] 2019-03-13 02:22
And how do I do something with it? xD

Mr. Xyfir <notifications@github.com> schrieb am Mi., 13. März 2019, 03:05:

**Comment by MrXyfir** [comment] 2019-03-13 16:14
You want to send mail from your server (and your domain) to Gmail correct? If so, smtp-server isn't really what you want. It's only for _receiving_ incoming mail. nodemailer itself should be enough to send mail wherever you need it.

The simplest option for you would be to use a sendmail transporter:

```ts
nodemailer.createTransport({ sendmail: true })
```

Now this kind of mail might be seen as spam unless you setup DKIM, SPF, and DMARC for your domain. To avoid all that, _don't_ send from your domain. Send from your Gmail and use their SMTP information for your transporter.

**Comment by severussnape357** [comment] 2019-03-13 21:01
thank you!

Am Mi., 13. März 2019 um 17:14 Uhr schrieb Mr. Xyfir <
notifications@github.com>:

**Comment by kaniho1** [comment] 2020-04-19 00:34
Hi, I'm new, and I don't understand where to get emails to gmail ...
I've seen them say "nodemailer.createTransport ({sendmail: true})"
but is it referred to in the smtp.js? I use the smtp.js of the example and to send the mail I use this:
`var nodemailer = require('nodemailer');

    console.log("Creating transport...");
    var transporter = nodemailer.createTransport({
      host: '127.0.0.1',
      port: 25,
      secure: false, // true for 465, false for other ports
    });

    let mailOptions = {
      from: '"yeahhh" <my@mail.com>',
      to: 'xxxxx@gmail.com',
      subject: 'subject',
      text: 'Ok, text...'
    };
	
    console.log("sending email", mailOptions);

    transporter.sendMail(mailOptions, function (error, info) {
      console.log("senMail returned!");
      if (error) {
        console.log("ERROR!!!!!!", error);
      } else {
        console.log('Email sent: ' + info.response);
		
      }
    });

    console.log("End of Script");`

**Comment by vinodhreddygs** [comment] 2020-04-23 07:47
> smtp-server

Hi,
Using the smtp-server Iam trying to receive mails. But Authentication is not happening.
Please check the below code snippet that iam using.

```
var SMTPServer = require('smtp-server').SMTPServer;

var server = new SMTPServer({
    tls:true,
    logger: true,
    onAuth(auth, session, callback) {
        console.log("Console in auth function>>>",auth);
        if (auth.username != config.mail_username || auth.password != config.mail_password) {
          return callback(new Error("Invalid username or password"));
        }
        console.log("Authentication successfull>>>")
        return callback();
    },
    onConnect(session, callback) {
        console.log("Console in onConnect function>>>",session);
        if (session.remoteAddress === "127.0.0.1") {
          return callback(new Error("No connections from localhost allowed"));
        }
        return callback(); // Accept the connection
    },
    onMailFrom(address, session, callback) {
        console.log("Received mail from function>>>",address);
        if (address.address !== "vinodhreddy33@gmail.com") {
          return callback(
            new Error("Only vinodhreddy33@gmail.com is allowed to send mail")
          );
        }
        return callback(); // Accept the address
    },
    onData(stream, session, callback) {
        console.log("Console at onData function>>>",onData);
        stream.pipe(process.stdout); // print message to console
        stream.on("end", callback);
      }
});
// mailListener.listen(465) // start listening
server.listen(465, function () {
console.log("starts listning on 465>>>")
})
server.on("error", err => {
    console.log("Error %s", err.message);
  });

server.on('error', err => {
    console.log("Error on server start",err.message);
  });

server.listen(465);
```
Thanks in advance

**Comment by varaprasadh** [comment] 2020-06-09 05:17
i have tried boiler plate code that nodemailer provided and changed receiver mail to main and used default test account created by nodemailer, after running it , it shows as sent and generated a preview url but didnt get mail to my gmail account!, checked in spam too.

**Comment by ujLion** [comment] 2020-07-23 23:33
In my case was the issue of `name` parameter not matching thus being rejected (i think) on the smtp server. So I had to specify the `name` parameter in the transport configuration as my domain e.g. `name=example.com` . Likewise, in case of the firebase mail extension: in the smtp connection uri, I appended `/?name=example.com`

**Comment by DaggieBlanqx** [comment] 2021-01-28 06:10
> In my case was the issue of `name` parameter not matching thus being rejected (i think) on the smtp server. So I had to specify the `name` parameter in the transport configuration as my domain e.g. `name=example.com` . Likewise, in case of the firebase mail extension: in the smtp connection uri, I appended `/?name=example.com`

This worked for me!

this.transporter = nodemailer.createTransport(
    `smtps://${process.env.mailUser}:${process.env.mailPass}@${
      process.env.mailHost
    }:465?name=example.com`
  );

**Comment by Devashish-Suthar** [comment] 2021-03-18 07:07
In my case, adding name to transporter object the issue is solved!
`nodemailer.createTransport({`
    name: SMTP_HOST, // mail.example.com or smtp.mail.com
    host: SMTP_HOST, // mail.example.com or smtp.mail.com
    port: SMTP_PORT, // 465
    secure: true,
    auth: {
        user: SMTP_USER, // username
        pass: SMTP_PASS // password
    },
    logger: true,
    debug: true
});`

**Comment by arihantdaga** [comment] 2021-03-21 04:51
> In my case, adding name to transporter object the issue is solved!

Worked for me too.

**Closed** 2021-06-12 12:59 UTC

**Comment by AndreBLima** [comment] 2022-09-02 18:28
> In my case, adding name to transporter object the issue is solved!
> 
> nodemailer.createTransport( { name: SMTP_HOST, // mail.example.com or smtp.mail.com host: SMTP_HOST, // mail.example.com or smtp.mail.com port: SMTP_PORT, // 465 secure: true, auth: { user: SMTP_USER, // username pass: SMTP_PASS // password }, logger: true, debug: true });

<3 try

**Comment by dosanias** [comment] 2023-10-26 10:49
Worked for me too. 

Thank you.

**Comment by gregg-cbs** [comment] 2024-04-27 13:09
You know what stumped me big time. **Gmail blocks emails that have localhost urls in them.**

So i was generating my urls based on my environment which was localhost and in the mailer i had links saying "click here to contact us", "view the webpage here" -> these urls were pointing to "http://localhost:5173" and gmail did not like that.

After removing them or changing them another random https:// url everything was fine.

**Comment by cesurSword** [comment] 2024-10-07 10:36
Hi
Just a quick tip
you might want to try the name parameter without mail. in front of it
'domain.com' rather than 'mail.domain.com' which solved the problem for me.
